### PR TITLE
fix: accumulate image manifests in oci_image_index

### LINKED ISSUE #638: multi arch images broken on 2.x
In the 2.x branch and respective releases the functionality to create multi arch images is broken due to jq overwriting the first manifest while creating the index manifest.

https://github.com/bazel-contrib/rules_oci/blob/0d90696187ab86b0ab73a7b03a163e661799a6e3/oci/private/image_index.sh.tpl#L27

Here the jq command should merge the existing manifest with the newly added one from the image. But instead it overrides the existing one. JQ has an explicit append to array operator _+=_ which is better suited in this context.

### PR DESCRIPTION
**Pull request by seh**
In the recent bazel-contrib/rules_oci#386, when we replaced use of the _yq_ tool with the _jq_ tool, we [translated the `oci_image_index` rule's accumulation of image manifests incorrectly](https://github.com/bazel-contrib/rules_oci/pull/386/files#r1646778569), such that we lose all but the last index that we add to the index.

In `jq`, [the _update-assignment_ operator](https://jqlang.github.io/jq/manual/#update-assignment) (`|=`) does not append to an array supplied as its left-hand context value automatically. Instead, one must use [a _complex assignment_](https://jqlang.github.io/jq/manual/#complex-assignments), mentioning the context value explicitly together with [the addition operator](https://jqlang.github.io/jq/manual/#addition).

See [the preceding discussion in the "docker" channel](https://bazelbuild.slack.com/archives/CA3NW13MH/p1718836203461049) of the "Bazel" Slack workspace a chronicle of discovering this defect.

Fixes #638.

### CODE REVIEW

**Review by thesayyn — APPROVED** [review]

**Comment by thesayyn** [comment]
would be nice to have a test for this.

**Comment by seh** [comment]
It appears that the lone CI workflow failure was due to a flaky server. I lack permission to run the workflow again. Can one of the maintainers please trigger that workflow to run again?

File: oci/private/image_index.sh.tpl [hunk 1]
```diff
@@ -24,7 +24,7 @@ function add_image() {
         local platform=$("${JQ}" -c '{"os": .os, "architecture": .architecture, "variant": .variant, "os.version": .["os.version"], "os.features": .["os.features"]} | with_entries(select( .value != null ))' "${image_path}/blobs/${config_blob_path}")
         "${JQ}" --argjson platform "${platform}" \
                 --argjson manifest "${manifest}" \
-                '.manifests |= [$manifest + {"platform": $platform}]'\
+                '.manifests |= . + [$manifest + {"platform": $platform}]'\
```
Comment (seh) [inline oci/private/image_index.sh.tpl:27]: I do like @tobiaskohlbau's use of `+=` in #637. Which do you prefer here?

Comment (thesayyn) [reply oci/private/image_index.sh.tpl:27]: += probably better, let's do that
